### ISSUE TITLE
Reconfigure legendary config to take a list instead of a single string

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#220]
In the `legendary` config we need to change the type from a single legendary entry per sim type i.e. : `composite: "7162" # Talbadar's Stratagem` to use combos instead. This could be done in a few different ways.

## Option 1
Change it to a list and insert them into gear with commas

```
legendary:
    covenants:
      kyrian:
        composite: 
          - "7729" # Pallid Command
          - "6982" # Shadowflame Prism
```

which would turn into:

```
head=veil_of_the_banshee_queen,id=186325,ilevel=259,gem_id=173130/187320,bonus_id=7729/6982
```

## Option 2
Alternatively since we know that legendaries are 1 covenant + 1 other we could actually just use the config to select the "other" legendary and assume with the other one is based on your covenant. This would be slightly less changes but less configurable if Blizzard changes their mind.
